// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function SelectFolder() {
  return window['go']['backend']['App']['SelectFolder']();
}

export function StartWatcher(arg1) {
  return window['go']['backend']['App']['StartWatcher'](arg1);
}
