// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function ListRepos() {
  return window['go']['backend']['App']['ListRepos']();
}

export function OpenRepository() {
  return window['go']['backend']['App']['OpenRepository']();
}

export function RemoveRepository(arg1) {
  return window['go']['backend']['App']['RemoveRepository'](arg1);
}

export function ToggleWatcher(arg1, arg2) {
  return window['go']['backend']['App']['ToggleWatcher'](arg1, arg2);
}

export function VerifyIntegration(arg1) {
  return window['go']['backend']['App']['VerifyIntegration'](arg1);
}
