// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {git} from '../models';
import {backend} from '../models';

export function DomReady(arg1:context.Context):Promise<void>;

export function ListRepos():Promise<Array<git.RepositoryInfo>>;

export function OpenRepository():Promise<backend.OpenRepositoryResult>;

export function RemoveRepository(arg1:string):Promise<void>;

export function ToggleWatcher(arg1:string,arg2:boolean):Promise<void>;

export function VerifyIntegration(arg1:string):Promise<boolean>;
